name: Build and Publish the Docker image to Dockerhub.

on:
  workflow_call:
    inputs:
      gradle_tasks:
        type: string
        description: The Gradle tasks to execute
        required: true
    secrets:
      docker_hub_username:
        required: true
      docker_hub_password:
        required: true

env:
  version_format: "${{ github.event_name == 'pull_request' && format('${{major}}.${{minor}}.${{patch}}-pr-{0}', github.sha ) || '${major}.${minor}.${patch}' }}"

concurrency:
  # Limit to a single concurrent invocation to ensure tagging works correctly.
  group: influxdb-weather-ingestor
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Echo version format
        run: echo Version format is $version_format

      # Try updating to latest version of Docker to resolve 'Could not push image: missing content-length header for request:' issue.
      # https://forums.docker.com/t/unexpected-missing-content-length-header-for-request/145907/12
      - name: Check Docker Version
        run: docker --version

      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce

      - name: Check Docker Version
        run: docker --version

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Checkout history and tags for semantic version calculation

      - name: Determine semantic version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          version_format: ${{ env.version_format }}

      - name: Output semver debug information
        run: "echo SEMVER debug info: ${{ steps.semver.outputs.debug_output }}"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Login to Docker Hub
        run:  echo ${{ secrets.docker_hub_password }} | docker login --username ${{ secrets.docker_hub_username }} --password-stdin registry.hub.docker.com/library/eddgrant/influxdb-weather-ingestor

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew -Pversion="${{ steps.semver.outputs.version }}" ${{ inputs.gradle_tasks }}

      - name: Set tag value
        id: tag-value
        run: echo "TAG_VALUE=${{ github.event_name == 'pull_request' && steps.semver.outputs.version || steps.semver.outputs.version_tag }}" >> "$GITHUB_OUTPUT"

      - name: Echo tag value
        run: echo Tag value is ${{ steps.tag-value.outputs.TAG_VALUE }}

      - name: Push tag to repository
        run: |
          git tag -a ${{ steps.tag-value.outputs.TAG_VALUE }} ${{ github.sha }}
          git push origin ${{ steps.tag-value.outputs.TAG_VALUE }}