name: Build and Publish the Docker image to Dockerhub.

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Checkout history and tags for semantic version calculation

      - name: Determine semantic version
        id: semver
        uses: paulhatch/semantic-version@v5.3.0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew =P version=${{ steps.semver.outputs.version }}" test dockerBuild