name: Commit to main build and release

on:
  push:
    branches:
      - main

jobs:
  main-build-and-release:
    uses: ./.github/workflows/build-and-deploy.yaml
    permissions:
      actions: write
      checks: write
      contents: write
    with:
      gradle_tasks: check dockerPushVersion dockerPushLatest --stacktrace --warning-mode all
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      meteomatics_username: ${{ secrets.METEOMATICS_USERNAME }}
      meteomatics_password: ${{ secrets.METEOMATICS_PASSWORD }}

  update-docker-hub-documentation:
    needs: main-build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Docker Hub Documentation
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: eddgrant/influxdb-weather-ingestor
          short-description: A simple utility which obtains temperature data, based on UK postcode, and sends it to InfluxDB.
          enable-url-completion: true