name: Commit to main build and release

on:
  push:
    branches:
      - main

jobs:
  main-build-and-release:
    uses: ./.github/workflows/build-and-deploy.yaml
    permissions:
      actions: read
      checks: write
      contents: write

    with:
      gradle_tasks: check dockerPushVersion dockerPushLatest --stacktrace --warning-mode all
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      meteomatics_username: ${{ secrets.METEOMATICS_USERNAME }}
      meteomatics_password: ${{ secrets.METEOMATICS_PASSWORD }}