name: Pull Request build and release

on:
  pull_request:

jobs:
  pr-build-and-release:
    uses: ./.github/workflows/build-and-deploy.yaml
    permissions:
      actions: read
      checks: write
      contents: write

    with:
      gradle_tasks: check dockerPushVersion --stacktrace --warning-mode all
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      meteomatics_username: ${{ secrets.METEOMATICS_USERNAME }}
      meteomatics_password: ${{ secrets.METEOMATICS_PASSWORD }}