name: Pull Request build and release

on:
  pull_request:

jobs:
  pr-build:
    uses: ./.github/workflows/build-and-deploy.yaml
    with:
      gradle_tasks: test dockerPushVersion --stacktrace --warning-mode all