name: Run unit tests and publish their results

on:
  workflow_call:

jobs:
  run-tests-and-publish-results:
    permissions:
      actions: read
      checks: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew test

      # https://github.com/orgs/community/discussions/66910
    - name: Update Status Badge
      run: |
        repo_token="${{ secrets.GITHUB_TOKEN }}"
        workflow_file="unit-test.yaml"
        response=$(curl -X POST "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${workflow_file}/dispatches" \
            -H "Authorization: Bearer $repo_token" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$payload")
        echo "$response"

    - name: Upload test results artefacts
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: unit-test-results
        path: build/test-results/test

    - name: Publish Unit Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Unit Tests
        path: build/test-results/test/TEST-*.xml
        reporter: java-junit