name: Run unit tests and publish their results

on:
  workflow_call:

jobs:
  run-tests-and-publish-results:
    permissions:
      actions: read
      checks: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew test

    - name: Upload test results artefacts
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: unit-test-results
        path: build/test-results/test

    - name: Publish Unit Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Unit Tests
        path: build/test-results/test/TEST-*.xml
        reporter: java-junit
